# -*- coding: utf-8 -*-
"""Healthcare_Information_Assistant_TTS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BuiiPDzCdOYPbKtPoCqXLAbJf4mghvfx
"""

!pip install -qU langchain langchain-community langchain-google-genai langchain-huggingface faiss-cpu sentence-transformers pypdf

!pip install -q google-auth==2.49.0

from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_google_genai import ChatGoogleGenerativeAI

print("SUCCESS! Everything is ready.")

import os
import getpass

os.environ["GOOGLE_API_KEY"] = getpass.getpass(
    "Enter your Gemini API key: "
)

print("API key added successfully!")

llm = ChatGoogleGenerativeAI(
    model="gemini-3.6-flash"
)

response = llm.invoke(
    "What is healthcare information? Answer in one sentence."
)

# Extract only the text
if isinstance(response.content, list):
    answer = "".join(
        item.get("text", "")
        for item in response.content
        if isinstance(item, dict)
    )
else:
    answer = response.content

print(answer)

from langchain_core.documents import Document

healthcare_documents = [

    Document(
        page_content="""
        Diabetes is a chronic condition that affects how the body
        regulates blood glucose. Common symptoms may include increased
        thirst, frequent urination, increased hunger, unexplained weight
        changes, tiredness, and blurred vision. Some people may have few
        or no symptoms, particularly in the early stages.

        Diabetes management may involve healthy eating, physical activity,
        monitoring blood glucose when recommended, and medicines prescribed
        by a healthcare professional.
        """,
        metadata={"source": "Diabetes Information"}
    ),

    Document(
        page_content="""
        Hypertension, commonly called high blood pressure, occurs when
        blood pressure remains too high over time. High blood pressure
        often does not cause noticeable symptoms, which is why regular
        blood pressure measurement is important.

        Long-term uncontrolled hypertension can increase the risk of
        heart disease, stroke, kidney problems, and other complications.
        Management may include lifestyle changes and medicines prescribed
        by a healthcare professional.
        """,
        metadata={"source": "Hypertension Information"}
    ),

    Document(
        page_content="""
        A balanced diet provides carbohydrates, proteins, healthy fats,
        vitamins, minerals, fiber, and adequate fluids. Fruits,
        vegetables, whole grains, legumes, and appropriate protein
        sources can contribute to a balanced eating pattern.

        Individual nutritional needs vary depending on factors such as
        age, activity level, health conditions, and medications.
        Individualized dietary advice should be obtained from a qualified
        healthcare professional or registered dietitian.
        """,
        metadata={"source": "Nutrition Information"}
    ),

    Document(
        page_content="""
        Dehydration occurs when the body loses more fluid than it takes
        in. Possible signs include thirst, dry mouth, tiredness,
        dizziness, and reduced urination.

        Drinking adequate fluids can help prevent dehydration. Fluid
        needs can increase during illness, heavy exercise, hot weather,
        vomiting, or diarrhea. Severe symptoms or inability to keep
        fluids down require appropriate medical attention.
        """,
        metadata={"source": "Dehydration Information"}
    ),

    Document(
        page_content="""
        Regular physical activity can support cardiovascular health,
        muscle strength, bone health, sleep, and overall wellbeing.
        Activities can include walking, cycling, swimming, and
        strength exercises.

        Exercise should be appropriate for an individual's age, fitness
        level, health conditions, and physical abilities. People with
        medical concerns should seek professional advice before starting
        a new exercise program.
        """,
        metadata={"source": "Physical Activity Information"}
    ),

    Document(
        page_content="""
        Fever is an elevation in body temperature that can occur as part
        of the body's response to infection or other conditions.
        Symptoms associated with fever can include feeling hot, chills,
        sweating, weakness, or discomfort.

        The significance of a fever depends on factors such as age,
        duration, severity, and accompanying symptoms. Persistent,
        severe, or concerning fever should be evaluated by an appropriate
        healthcare professional.
        """,
        metadata={"source": "Fever Information"}
    ),

    Document(
        page_content="""
        Good sleep supports physical health, cognitive function, mood,
        and daily performance. Helpful sleep habits can include keeping
        a consistent sleep schedule, creating a comfortable sleep
        environment, limiting stimulating activities before bedtime,
        and avoiding excessive caffeine late in the day.

        Persistent sleep problems that interfere with daily life should
        be discussed with a healthcare professional.
        """,
        metadata={"source": "Sleep Information"}
    )
]

print("Healthcare knowledge base created!")
print("Number of documents:", len(healthcare_documents))

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=100
)

chunks = text_splitter.split_documents(
    healthcare_documents
)

print("Original documents:", len(healthcare_documents))
print("Total chunks:", len(chunks))

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

print("Embedding model loaded successfully!")

from langchain_community.vectorstores import FAISS

vectorstore = FAISS.from_documents(
    chunks,
    embeddings
)

print("FAISS vector database created successfully!")

retriever = vectorstore.as_retriever(
    search_kwargs={"k": 3}
)

print("Retriever created successfully!")

question = "What are the symptoms of diabetes?"

results = retriever.invoke(question)

for i, result in enumerate(results):
    print("=" * 70)
    print("RESULT", i + 1)
    print("SOURCE:", result.metadata["source"])
    print(result.page_content)

from langchain_core.prompts import ChatPromptTemplate

prompt = ChatPromptTemplate.from_template("""
You are a Healthcare Information Assistant.

Your purpose is to provide general educational healthcare information.

IMPORTANT RULES:
1. Use ONLY the information provided in the context.
2. Do not invent medical facts.
3. Do not diagnose the user.
4. Do not prescribe medicines or give personalized treatment plans.
5. If the answer is not available in the context, say:
   "I don't have enough information in the provided healthcare sources."
6. Give clear and simple explanations.
7. For personal medical advice, recommend consulting a qualified healthcare professional.

CONTEXT:
{context}

QUESTION:
{question}

ANSWER:
""")

print("RAG prompt created successfully!")

def extract_text(response):
    if isinstance(response.content, list):
        return "".join(
            item.get("text", "")
            for item in response.content
            if isinstance(item, dict)
        )
    return response.content


def healthcare_rag(question):

    # 1. Retrieve relevant documents
    retrieved_docs = retriever.invoke(question)

    # 2. Combine retrieved information
    context = "\n\n".join(
        doc.page_content
        for doc in retrieved_docs
    )

    # 3. Create the prompt
    formatted_prompt = prompt.invoke({
        "context": context,
        "question": question
    })

    # 4. Ask Gemini
    response = llm.invoke(formatted_prompt)

    # 5. Extract answer
    answer = extract_text(response)

    # 6. Get sources
    sources = list(dict.fromkeys(
        doc.metadata.get("source", "Unknown")
        for doc in retrieved_docs
    ))

    return answer, sources


print("Healthcare RAG function created successfully!")

question = "What are the symptoms of diabetes?"

answer, sources = healthcare_rag(question)

print("QUESTION:")
print(question)

print("\nANSWER:")
print(answer)

print("\nSOURCES:")
for source in sources:
    print("-", source)

questions = [
    "What is hypertension?",
    "What are the signs of dehydration?",
    "Why is sleep important?",
    "What are the benefits of physical activity?"
]

for question in questions:

    answer, sources = healthcare_rag(question)

    print("=" * 80)
    print("QUESTION:", question)
    print("\nANSWER:")
    print(answer)

    print("\nSOURCES:")
    for source in sources:
        print("-", source)

    print()

while True:

    question = input("\nAsk a healthcare question (type 'exit' to stop): ")

    if question.lower() == "exit":
        print("Healthcare Assistant stopped.")
        break

    answer, sources = healthcare_rag(question)

    print("\nANSWER:")
    print(answer)

    print("\nSOURCES:")
    for source in sources:
        print("-", source)

!pip install -q gradio

print("Gradio installed successfully!")

def chatbot_response(question):

    if not question.strip():
        return "Please enter a healthcare question.", ""

    answer, sources = healthcare_rag(question)

    source_text = "Sources:\n" + "\n".join(
        f"- {source}" for source in sources
    )

    return answer, source_text


print("Chatbot function created successfully!")

import gradio as gr

with gr.Blocks(title="Healthcare Information Assistant") as demo:

    gr.Markdown(
        """
        # 🏥 Healthcare Information Assistant

        Ask questions about general healthcare topics.
        """
    )

    question = gr.Textbox(
        label="Your Question",
        placeholder="Example: What are the symptoms of diabetes?",
        lines=2
    )

    ask_button = gr.Button("🔍 Ask")

    answer = gr.Textbox(
        label="Answer",
        lines=8
    )

    sources = gr.Textbox(
        label="Sources",
        lines=4
    )

    gr.Markdown(
        """
        ⚠️ **Disclaimer:** This assistant provides general educational
        healthcare information. It does not diagnose conditions or
        prescribe treatment. For personal medical advice, consult a
        qualified healthcare professional.
        """
    )

    ask_button.click(
        fn=chatbot_response,
        inputs=question,
        outputs=[answer, sources]
    )

print("Healthcare chatbot interface created successfully!")

demo.launch(share=True)

retriever = vectorstore.as_retriever(
    search_kwargs={"k": 2}
)

print("Retriever updated successfully!")
print("Number of documents retrieved: 2")

question = "Why is sleep important?"

results = retriever.invoke(question)

for i, result in enumerate(results):
    print("=" * 70)
    print("RESULT", i + 1)
    print("SOURCE:", result.metadata["source"])
    print(result.page_content)

answer, sources = healthcare_rag(
    "Why is sleep important?"
)

print("ANSWER:")
print(answer)

print("\nSOURCES:")
for source in sources:
    print("-", source)

!pip install -q gTTS

print("TTS installed successfully!")

from gtts import gTTS
import os

def text_to_speech(text):
    audio_file = "/content/healthcare_answer.mp3"

    tts = gTTS(
        text=text,
        lang="en"
    )

    tts.save(audio_file)

    return audio_file

print("Text-to-Speech function created successfully!")

def chatbot_response_tts(question):

    if not question.strip():
        return "Please enter a healthcare question.", "", None

    # Get answer from RAG
    answer, sources = healthcare_rag(question)

    # Prepare sources
    source_text = "Sources:\n" + "\n".join(
        f"- {source}" for source in sources
    )

    # Convert answer to speech
    audio_file = text_to_speech(answer)

    return answer, source_text, audio_file


print("RAG + TTS chatbot function created successfully!")

import gradio as gr

with gr.Blocks(title="Healthcare Information Assistant with TTS") as demo_tts:

    gr.Markdown(
        """
        # 🏥 Healthcare Information Assistant

        Ask a healthcare question and listen to the answer.
        """
    )

    question = gr.Textbox(
        label="Your Question",
        placeholder="Example: What are the symptoms of diabetes?",
        lines=2
    )

    ask_button = gr.Button("🔍 Ask")

    answer = gr.Textbox(
        label="Answer",
        lines=8
    )

    sources = gr.Textbox(
        label="Sources",
        lines=4
    )

    audio = gr.Audio(
        label="🔊 Listen to the Answer",
        type="filepath"
    )

    gr.Markdown(
        """
        ⚠️ **Disclaimer:** This assistant provides general educational
        healthcare information. It does not diagnose conditions or
        prescribe treatment. For personal medical advice, consult a
        qualified healthcare professional.
        """
    )

    ask_button.click(
        fn=chatbot_response_tts,
        inputs=question,
        outputs=[answer, sources, audio]
    )

print("Healthcare chatbot with TTS created successfully!")

demo_tts.launch(share=True)